# Example that calculates induced velocity distribution using only numpy vectorization

## Setup environment

In [1]:
from src import Wing, FlightCondition, WingPool, Simulation, PostProcessing, load_folder

airfoils_data, _ = load_folder("sample_airfoils")
# print(airfoils_data)

wing = Wing(
    spans=[1, 0.5],
    chords=[1, 0.5, 0.4],
    offsets=[0, 0, 0],
    twist_angles=[0, 0, 0],
    dihedral_angles=[0, 0, 0],
    airfoils=["NACA4424", "NACA4424", "NACA4412"],
    surface_name="wing",
    N_panels=4,
    distribution_type="cosine",
    sweep_check=False,
)
wing.generate_mesh()  # Generate wing simulation elements
flight_condition = FlightCondition(
    V_inf=20,
    nu=1.5e-5,
    rho=1.225,
    angles_of_attack=[alpha for alpha in range(1)],
    h=0,
    ground_effect_check=False,
)
wing.setup_airfoil_data(flight_condition, airfoils_data)  # Assign airfoil data to wing

# Link wing that will be simulated with flight condition
wing_pool = WingPool(wing_list=[wing], flight_condition=flight_condition)

0.07471440384036197
[ 0.          0.         -1.43589335]
0.07471440384036197
[0.         0.         0.33592634]
0.07471440384036197
[0.         0.         0.03294638]
0.07471440384036197
[0.       0.       0.031048]
0.060235724989640936
[0.         0.         0.10552881]
0.060235724989640936
[ 0.         0.        -0.4818858]
0.060235724989640936
[0.         0.         0.13541409]
0.060235724989640936
[0.         0.         0.06659885]
0.04494653485465563
[0.         0.         0.01544567]
0.04494653485465563
[0.         0.         0.15748641]
0.04494653485465563
[ 0.          0.         -0.96932516]
0.04494653485465563
[0.         0.         0.64583606]
0.035957227883724505
[0.         0.         0.00641838]
0.035957227883724505
[0.         0.         0.03249025]
0.035957227883724505
[0.         0.         0.06698284]
0.035957227883724505
[ 0.          0.         -0.28765782]
0.07471440384036197
[ 0.         -0.          0.85653375]
0.07471440384036197
[0.         0.         0.156941

In [2]:
from src.utils.velocity import get_induced_velocity_distribution
import numpy as np
import numpy.linalg as npla

collocation_points = wing.collocation_points
vertice_points = wing.vertice_points
mac = np.array(wing.cp_macs)
v_inf_array = np.array(flight_condition.v_inf_list[0])

v_ij_distr = get_induced_velocity_distribution(collocation_points, wing.cp_macs, vertice_points, v_inf_array, wing.surface_name, False, 0)
print(v_ij_distr)

# ind_velocities_dict = wing_pool.calculate_induced_velocities(v_inf_array)
# for k, v in ind_velocities_dict.items():
#     print(f"{k}: {v}")

0.07471440384036197
[ 0.          0.         -1.43589335]
0.07471440384036197
[0.         0.         0.33592634]
0.07471440384036197
[0.         0.         0.03294638]
0.07471440384036197
[0.       0.       0.031048]
0.060235724989640936
[0.         0.         0.10552881]
0.060235724989640936
[ 0.         0.        -0.4818858]
0.060235724989640936
[0.         0.         0.13541409]
0.060235724989640936
[0.         0.         0.06659885]
0.04494653485465563
[0.         0.         0.01544567]
0.04494653485465563
[0.         0.         0.15748641]
0.04494653485465563
[ 0.          0.         -0.96932516]
0.04494653485465563
[0.         0.         0.64583606]
0.035957227883724505
[0.         0.         0.00641838]
0.035957227883724505
[0.         0.         0.03249025]
0.035957227883724505
[0.         0.         0.06698284]
0.035957227883724505
[ 0.          0.         -0.28765782]
[[[ 0.          0.         -1.43589335]
  [ 0.          0.          0.33592634]
  [ 0.          0.          0

## Using only numpy vectorization

In [22]:
mac = np.array(wing.cp_macs)
mac = mac[:, np.newaxis, np.newaxis]

ri1j = (
    collocation_points[:, np.newaxis, :] - vertice_points[np.newaxis, :-1, :]
)
ri2j = (
    collocation_points[:, np.newaxis, :] - vertice_points[np.newaxis, 1:, :]
)
ri1j_abs = npla.norm(ri1j, axis=2)[:, :, np.newaxis]
ri2j_abs = npla.norm(ri2j, axis=2)[:, :, np.newaxis]
r1_cross_prod = np.cross(v_inf_array, ri1j)
r2_cross_prod = np.cross(v_inf_array, ri2j)
r1_dot_prod = np.sum(v_inf_array * ri1j, axis=2)[:, :, np.newaxis]
r2_dot_prod = np.sum(v_inf_array * ri2j, axis=2)[:, :, np.newaxis]
r12_cross_prod = np.cross(ri1j, ri2j)
r12_dot_prod = np.sum(ri1j * ri2j, axis=2)[:, :, np.newaxis]

velocities = (
    mac / (4 * np.pi)
    * (
        r2_cross_prod / (ri2j_abs * (ri2j_abs - r2_dot_prod))
        - r1_cross_prod / (ri1j_abs * (ri1j_abs - r1_dot_prod))
    )
)
bound_vortex_den = ri1j_abs * ri2j_abs * (ri1j_abs * ri2j_abs + r12_dot_prod)

threshold = 1e-10
mask = np.isclose(bound_vortex_den, 0, atol=threshold)

with np.errstate(divide='ignore', invalid='ignore'):
    bound_vortex = np.where(
        mask,
        np.zeros(mask.shape),
        (mac / (4 * np.pi) * ((ri1j_abs + ri2j_abs) * r12_cross_prod / bound_vortex_den)),
    )
# velocities += bound_vortex

# print(ri1j)
# print(r1_cross_prod[0][0])
# print(np.cross(v_inf_array, [-0.00837341, 0.0669873,  0.        ]))
# print(r1_dot_prod)
# print(np.dot(v_inf_array, [-0.00837341, 0.0669873,  0.        ]))
# print(r12_dot_prod)
# print(np.dot(ri1j[0][1], ri2j[0][1]))
# print(velocities)
# print(mask)
print(velocities)
print(bound_vortex)

[[[ 0.          0.         -1.43589335]
  [ 0.          0.          0.33592634]
  [ 0.          0.          0.03294638]
  [ 0.          0.          0.03274531]]

 [[ 0.          0.          0.10552881]
  [ 0.          0.         -0.4818858 ]
  [ 0.          0.          0.13541409]
  [ 0.          0.          0.0699278 ]]

 [[ 0.          0.          0.01544567]
  [ 0.          0.          0.15748641]
  [ 0.          0.         -0.96932516]
  [ 0.          0.          0.67026416]]

 [[ 0.          0.          0.00653764]
  [ 0.          0.          0.03348774]
  [ 0.          0.          0.07100055]
  [ 0.          0.         -0.28765782]]]
[[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00 -7.01851323e-18]
  [ 0.00000000e+00  0.00000000e+00 -4.03125263e-18]
  [ 0.00000000e+00  0.00000000e+00 -1.69731127e-03]]

 [[ 0.00000000e+00  0.00000000e+00 -2.45016632e-18]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00 -4.

In [4]:
print(velocities-v_ij_distr)

[[[ 0.          0.          0.        ]
  [ 0.          0.         -0.06509815]
  [ 0.          0.         -0.01312657]
  [ 0.          0.         -0.01528892]]

 [[ 0.          0.          0.02536564]
  [ 0.          0.          0.        ]
  [ 0.          0.         -0.03437116]
  [ 0.          0.         -0.02485602]]

 [[ 0.          0.          0.01022959]
  [ 0.          0.          0.0535712 ]
  [ 0.          0.          0.        ]
  [ 0.          0.         -0.10962473]]

 [[ 0.          0.          0.00716598]
  [ 0.          0.          0.02360857]
  [ 0.          0.          0.02176784]
  [ 0.          0.          0.        ]]]


In [5]:
print(f'ri1j_abs: {ri1j_abs}')
print(f'ri2j_abs: {ri2j_abs}')
print(f'r1_cross_prod: {r1_cross_prod}')
print(f'r2_cross_prod: {r2_cross_prod}')
print(f'r1_dot_prod: {r1_dot_prod}')
print(f'r2_dot_prod: {r2_dot_prod}')
print(f'r12_cross_prod: {r12_cross_prod}')
print(f'r12_dot_prod: {r12_dot_prod}')

ri1j_abs: [[[0.06750861]
  [0.18443695]
  [0.68832806]
  [0.94027361]]

 [[0.50389111]
  [0.25194555]
  [0.25194555]
  [0.50389111]]

 [[0.94027361]
  [0.68832806]
  [0.18443695]
  [0.06750861]]

 [[1.25753976]
  [1.00562869]
  [0.50191041]
  [0.2503123 ]]]
ri2j_abs: [[[0.18443695]
  [0.68832806]
  [0.94027361]
  [1.43999427]]

 [[0.25194555]
  [0.25194555]
  [0.50389111]
  [1.00382083]]

 [[0.68832806]
  [0.18443695]
  [0.06750861]
  [0.56796864]]

 [[1.00562869]
  [0.50191041]
  [0.2503123 ]
  [0.2503123 ]]]
r1_cross_prod: [[[ 0.        -0.         0.0669873]
  [ 0.         0.        -0.1830127]
  [ 0.         0.        -0.6830127]
  [ 0.         0.        -0.9330127]]

 [[ 0.        -0.         0.5      ]
  [ 0.        -0.         0.25     ]
  [ 0.         0.        -0.25     ]
  [ 0.         0.        -0.5      ]]

 [[ 0.        -0.         0.9330127]
  [ 0.        -0.         0.6830127]
  [ 0.        -0.         0.1830127]
  [ 0.         0.        -0.0669873]]

 [[ 0.        -0.  

In [21]:
mac = np.array(wing.cp_macs)
mac = mac[:, np.newaxis, np.newaxis]
mac
# mac / (4 * np.pi)

array([[[0.93888889]],

       [[0.75694444]],

       [[0.56481481]],

       [[0.45185185]]])